[tool.poetry]
name = "max-distance"
version = "0.1.0"
description = "small thingie to calc the max distance between the equal elements in the given array"
authors = ["Peter A."]

[tool.poetry.dependencies]
python = "^3.9"
python-fire = "^0.1.0"
beartype = "^0.8.1"
fire = "^0.4.0"
click = "^8.0.1"
mypy = "^0.910"
click-help-colors = "^0.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
solve-md = 'max_distance.main:solve'