[tool.poetry]
name = "max-distance"
version = "0.1.0"
description = "small thingie to calc the max distance between the equal elements in the given array"
authors = ["Peter A."]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
beartype = "^0.8.1"
numpy = "^1.21.2"
plumbum = "^1.7.0"
cytoolz = "^0.11.0"
python-box = "^5.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
solve-md = 'max_distance.main:run'